### ISSUE TITLE
Module stability

### ISSUE THREAD

**Issue by carlotaprat** [Giphy/giphy-ios-sdk#188]
Seems like module stability is not provided anymore or broken. For now, I'm forced to use version 2.1.10 because I can't use Swift 5.5
Any thoughts?

**Comment by cgmaier** [comment]
hey @carlotaprat apologies for the late reply. as I said in a comment [here](https://github.com/Giphy/giphy-ios-sdk/issues/190#issuecomment-1021851789), this appears to be due to updates to Swift 5.5. on the bright side, it's been quite a while since it's happened with a Swift update. 
 
wish there was something we could do on our end (if you have any ideas let us know!). thanks

cc @ALexanderLonsky
