### ISSUE TITLE
downloadAsset get GiphyYYImage very slow

### ISSUE THREAD

**Issue by Nnnnnnnnnical** [Giphy/giphy-ios-sdk#198]
## Describe your question in detail.
(Describe the use case or problem you are trying to solve in detail.)

```
func didSelectMedia(giphyViewController: GiphyViewController, media: GPHMedia) {

     guard let url = media.url(rendition: giphyViewController.renditionType, fileType: .webp) else { return }
     GPHCache.shared.downloadAsset(url) { (image, error) in
            // image is GiphyYYImage based on YYImage
     }
```
Use this to get GiphyYYImage is so slow. I test this in the example project,some gifs need a few second or can not show in a few minutes.
GiphyYYImage is used to improve performance and reduce traffic requests. But it doesn't seem to work....

![企业微信截图_f06ed05d-35e3-4108-8429-1b3e42875906](https://user-images.githubusercontent.com/34621967/157885712-3146d7d3-2fab-48db-86db-f715d50b33a2.png)

Maybe there is something wrong with my usage, any advice would be greatly appreciated

Maybe

**Comment by cgmaier** [comment]
hey @Nnnnnnnnnical do you experience slow loads as well when using the `GiphyViewController`? 

The `GiphyViewController` uses the same underlying download/playback mechanism, though it could _and should_ be even faster loading an asset out of that context (via the `GPHCache.downloadAsset` call) because of the cache.  

Are you clearing the cache anywhere?

**Comment by Nnnnnnnnnical** [comment]
yes，i found it use clearing the cache。Thank you for your answer

**Comment by Nnnnnnnnnical** [comment]
And i have another question: How to disable long press gesture in mediaView？

**Comment by Nnnnnnnnnical** [comment]
I Have found it，“showAttribution”......
