### ISSUE TITLE
Why is 'Giphy.configure(apiKey: "") not listed in the Swift Example? Where do we put this? 

### ISSUE THREAD

**Issue by thecavilnator** [Giphy/giphy-ios-sdk#204]
## Describe your question in detail.
(Describe the use case or problem you are trying to solve in detail.)

**Comment by cgmaier** [comment]
hey @thecavilnator - I've made a ticket to add it back to the example apps. we try not to leave our internal API keys in the example app code and must have just deleted the line on accident, rather than including it with empty quotes. 

the `configure` call is necessary at least once per launch of an app instance before you present the `GiphyViewController` or the `GiphyGridController`. it's safe to call it multiple times.

**Comment by cgmaier** [comment]
we've added it back to the example apps! thanks!
